### ISSUE TITLE
No Table of Contents in book PDF

### ISSUE THREAD

**Issue by shakthimaan** [yinyanghu/XeLatex-Template#1]
In the generated PDF for a book using xelatex, there is no table of contents, even though there are chapters listed in them. What could I be missing?

**Comment by yinyanghu** [comment]
Probably you are right. This is an old template and I won't use it anymore, so I don't maintain it.
BTW. If you are not gonna write CJK characters in Latex, you would be better to use LaTex directly instead of XeLaTex.

**Comment by shakthimaan** [comment]
I am experimenting with Indian languages. Would it be possible to provide a new template, or a fix for the same?

Thanks for your reply.

**Comment by yinyanghu** [comment]
I have no idea for Indian language, but if you wanna have a table of contents, I think it should be the same thing with common Latex. Please go to StackOverflow to look for answers.
